#Name of the workflow
name: My Test Workflow

#define the trigger events
on: [push]

# Jobs run in parallel by default, each runs steps in sequence
jobs:
    # Job to print something out
    say-hello:
        runs-on: ubuntu-latest
        steps:
            - run: echo "Hello, Github Actions!"
    
    run-python-test:
        needs: [say-hello]
        runs-on: ubuntu-latest
        steps:
            - name: Checkout this repo
              uses: actions/checkout@v4
             
            - name: Install dependencies
              run: sudo apt install -y build-essential python3
             
            - run: pwd
            
            - name: run test.py
              run: python3 test.py
        